/*
 * Created on 2023-10-18 ( 14:00:04 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Categories"
 *
 * @author Telosys
 *
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
@Table(name="Categories", schema="dbo", catalog="BookWorm" )
public class Categories implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="CategoryId", nullable=false)
    private Integer    categoryid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="Name", length=100)
    private String     name ;

    @Column(name="Description", length=255)
    private String     description ;

    @Temporal(TemporalType.DATE)
    @Column(name="DateAdded")
    private Date       dateadded ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="categories")
    private List<Typebooks> listOfTypebooks ; 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(categoryid);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(description);
        sb.append("|");
        sb.append(dateadded);
        return sb.toString(); 
    } 

}
