/*
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Detailbookings"
 *
 * @author Telosys
 *
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
@Table(name="DetailBookings", schema="dbo", catalog="BookWorm" )
public class Detailbookings implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="DBId", nullable=false, length=10)
    private String     dbid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="BookId", nullable=false)
    private Integer    bookid ;

    @Column(name="BookingId", nullable=false, length=10)
    private String     bookingid ;

    @Column(name="Quantity", nullable=false)
    private Integer    quantity ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="BookingId", referencedColumnName="BookingId", insertable=false, updatable=false)
    private Bookings   bookings ; 

    @OneToMany(mappedBy="detailbookings")
    private List<Evaluates> listOfEvaluates ; 

    @ManyToOne
    @JoinColumn(name="BookId", referencedColumnName="BookId", insertable=false, updatable=false)
    private Books      books ; 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(dbid);
        sb.append("|");
        sb.append(bookid);
        sb.append("|");
        sb.append(bookingid);
        sb.append("|");
        sb.append(quantity);
        return sb.toString(); 
    } 

}
