/*
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Discountcodes"
 *
 * @author Telosys
 *
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
@Table(name="DiscountCodes", schema="dbo", catalog="BookWorm" )
public class Discountcodes implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="DiscountCodeId", nullable=false)
    private Integer    discountcodeid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="SaleId", nullable=false, length=10)
    private String     saleid ;

    @Column(name="UserId", nullable=false, length=10)
    private String     userid ;

    @Temporal(TemporalType.DATE)
    @Column(name="StartDiscount")
    private Date       startdiscount ;

    @Temporal(TemporalType.DATE)
    @Column(name="EndDiscount")
    private Date       enddiscount ;

    @Column(name="isDelete")
    private Boolean    isdelete ;

    @Column(name="MinPrice")
    private Double     minprice ;

    @Column(name="Status", length=50)
    private String     status ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="UserId", referencedColumnName="Userid", insertable=false, updatable=false)
    private Account    account ; 

    @ManyToOne
    @JoinColumn(name="SaleId", referencedColumnName="CouoponCode", insertable=false, updatable=false)
    private Sales      sales ; 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(discountcodeid);
        sb.append("|");
        sb.append(saleid);
        sb.append("|");
        sb.append(userid);
        sb.append("|");
        sb.append(startdiscount);
        sb.append("|");
        sb.append(enddiscount);
        sb.append("|");
        sb.append(isdelete);
        sb.append("|");
        sb.append(minprice);
        sb.append("|");
        sb.append(status);
        return sb.toString(); 
    } 

}
