/*
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Evaluates"
 *
 * @author Telosys
 *
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
@Table(name="Evaluates", schema="dbo", catalog="BookWorm" )
public class Evaluates implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="EvaluateId", nullable=false)
    private Integer    evaluateid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="DBId", nullable=false, length=10)
    private String     dbid ;

    @Column(name="Rating")
    private Integer    rating ;

    @Column(name="ReviewText", nullable=false, length=2555)
    private String     reviewtext ;

    @Temporal(TemporalType.DATE)
    @Column(name="EvaluateDate")
    private Date       evaluatedate ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="DBId", referencedColumnName="DBId", insertable=false, updatable=false)
    private Detailbookings detailbookings ; 

    @OneToMany(mappedBy="evaluates")
    private List<Imageevaluates> listOfImageevaluates ; 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(evaluateid);
        sb.append("|");
        sb.append(dbid);
        sb.append("|");
        sb.append(rating);
        sb.append("|");
        sb.append(reviewtext);
        sb.append("|");
        sb.append(evaluatedate);
        return sb.toString(); 
    } 

}
