/*
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Payments"
 *
 * @author Telosys
 *
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
@Table(name="Payments", schema="dbo", catalog="BookWorm" )
public class Payments implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="PaymentId", nullable=false, length=10)
    private String     paymentid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="BookingId", nullable=false, length=10)
    private String     bookingid ;

    @Temporal(TemporalType.DATE)
    @Column(name="CreateAt", nullable=false)
    private Date       createat ;

    @Column(name="Status", nullable=false, length=20)
    private String     status ;

    @Column(name="PAId", nullable=false, length=10)
    private String     paid ;

    @Column(name="Type")
    private Boolean    type ;

    @Column(name="AddressUserId", nullable=false, length=10)
    private String     addressuserid ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="AddressUserId", referencedColumnName="AddressUserId", insertable=false, updatable=false)
    private Addressusers addressusers ; 

    @ManyToOne
    @JoinColumn(name="PAId", referencedColumnName="PAId", insertable=false, updatable=false)
    private Paymentaccounts paymentaccounts ; 

    @ManyToOne
    @JoinColumn(name="BookingId", referencedColumnName="BookingId", insertable=false, updatable=false)
    private Bookings   bookings ; 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(paymentid);
        sb.append("|");
        sb.append(bookingid);
        sb.append("|");
        sb.append(createat);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(paid);
        sb.append("|");
        sb.append(type);
        sb.append("|");
        sb.append(addressuserid);
        return sb.toString(); 
    } 

}
