/*
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import javax.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Sales"
 *
 * @author Telosys
 *
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
@Table(name="Sales", schema="dbo", catalog="BookWorm" )
public class Sales implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="CouoponCode", nullable=false, length=10)
    private String     couoponcode ;

    //--- ENTITY DATA FIELDS 
    @Column(name="PromotionName", length=250)
    private String     promotionname ;

    @Temporal(TemporalType.DATE)
    @Column(name="CreateAt")
    private Date       createat ;

    @Column(name="Descriptions", length=255)
    private String     descriptions ;

    @Column(name="DiscountPercentage")
    private BigDecimal discountpercentage ;

    @Column(name="Statuses", length=20)
    private String     statuses ;

    @Column(name="IntendFor", length=50)
    private String     intendfor ;

    @Column(name="ShopId")
    private Integer    shopid ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="sales")
    private List<Discountcodes> listOfDiscountcodes ; 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(couoponcode);
        sb.append("|");
        sb.append(promotionname);
        sb.append("|");
        sb.append(createat);
        sb.append("|");
        sb.append(descriptions);
        sb.append("|");
        sb.append(discountpercentage);
        sb.append("|");
        sb.append(statuses);
        sb.append("|");
        sb.append(intendfor);
        sb.append("|");
        sb.append(shopid);
        return sb.toString(); 
    } 

}
