/*
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Writtingmasters"
 *
 * @author Telosys
 *
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
@Table(name="WrittingMasters", schema="dbo", catalog="BookWorm" )
public class Writtingmasters implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="WrittingMasterId", nullable=false)
    private Integer    writtingmasterid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="NameWM", length=50)
    private String     namewm ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="writtingmasters")
    private List<Writers> listOfWriters ; 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(writtingmasterid);
        sb.append("|");
        sb.append(namewm);
        return sb.toString(); 
    } 

}
