/*
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Writers"
 *
 * @author Telosys
 *
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
@Table(name="Writers", schema="dbo", catalog="BookWorm" )
public class Writers implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="WriteId", nullable=false)
    private Integer    writeid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="WrittingMasterId", nullable=false)
    private Integer    writtingmasterid ;

    @Column(name="BookId", nullable=false)
    private Integer    bookid ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="BookId", referencedColumnName="BookId", insertable=false, updatable=false)
    private Books      books ; 

    @ManyToOne
    @JoinColumn(name="WrittingMasterId", referencedColumnName="WrittingMasterId", insertable=false, updatable=false)
    private Writtingmasters writtingmasters ; 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(writeid);
        sb.append("|");
        sb.append(writtingmasterid);
        sb.append("|");
        sb.append(bookid);
        return sb.toString(); 
    } 

}
