/*
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.DATN_BookWorms.entities;

import java.io.Serializable;

import jakarta.persistence.Entity;

import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Authorities"
 *
 * @author Lê Chí Thiên
 *
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
@Table(name = "Authorities")
public class Authorities implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id 
	private String authorityid;
	@ManyToOne @JoinColumn(name = "userid")
	private Account account;
	@ManyToOne  @JoinColumn(name = "roleid")
	private Roles roles;
	public Roles getRoles() {
		// TODO Auto-generated method stub
		return this.roles;
	}

}
