/*
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.DATN_BookWorms.entities;

import java.io.Serializable;

import jakarta.persistence.Entity;

import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Entity
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Authorities")
public class Authority implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id 
	public String authorityid;

	@ManyToOne @JoinColumn(name = "userid")
	public Account account;

	// TODO Auto-generated method stub
	@ManyToOne  @JoinColumn(name = "roleid")
	public Role role;

}
