/*
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.DATN_BookWorms.entities;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Discountcodes"
 *
 * @author Telosys
 *
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
@Table(name="Discountcodes" )
public class Discountcodes implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    public Integer    discountcodeid ;

    //--- ENTITY DATA FIELDS 
    public String     saleid ;

    public String     userid ;

    @Temporal(TemporalType.DATE)
    public Date       startdiscount ;

    @Temporal(TemporalType.DATE)
    public Date       enddiscount ;

    public Boolean    isdelete ;



    @Column(name="status", length=50)
    public String     status ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="Userid", referencedColumnName="Userid", insertable=false, updatable=false)
    public Account    account ; 

    @ManyToOne
    @JoinColumn(name="Saleid", referencedColumnName="CouoponCode", insertable=false, updatable=false)
    public Sales      sales ; 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(discountcodeid);
        sb.append("|");
        sb.append(saleid);
        sb.append("|");
        sb.append(userid);
        sb.append("|");
        sb.append(startdiscount);
        sb.append("|");
        sb.append(enddiscount);
        sb.append("|");
        sb.append(isdelete);
        sb.append("|");
        sb.append(status);
        return sb.toString(); 
    }

	public Integer getDiscountcodeid() {
		return discountcodeid;
	}

	public void setDiscountcodeid(Integer discountcodeid) {
		this.discountcodeid = discountcodeid;
	}

	public String getSaleid() {
		return saleid;
	}

	public void setSaleid(String saleid) {
		this.saleid = saleid;
	}

	public String getUserid() {
		return userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public Date getStartdiscount() {
		return startdiscount;
	}

	public void setStartdiscount(Date startdiscount) {
		this.startdiscount = startdiscount;
	}

	public Date getEnddiscount() {
		return enddiscount;
	}

	public void setEnddiscount(Date enddiscount) {
		this.enddiscount = enddiscount;
	}

	public Boolean getIsdelete() {
		return isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Account getAccount() {
		return account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Sales getSales() {
		return sales;
	}

	public void setSales(Sales sales) {
		this.sales = sales;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	} 

}