/*
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.DATN_BookWorms.entities;

import java.io.Serializable;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Hassales"
 *
 * @author Telosys
 *
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
@Table(name="hassales", schema="dbo", catalog="bookworm" )
public class Hassales implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="hassaleid", nullable=false)
    private Integer    hassaleid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="bookid", nullable=false)
    private Integer    bookid ;

    @Column(name="saleid", nullable=false, length=10)
    private String     saleid ;

    @Temporal(TemporalType.DATE)
    @Column(name="starttime")
    private Date       starttime ;

    @Temporal(TemporalType.DATE)
    @Column(name="endtime")
    private Date       endtime ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="bookid", referencedColumnName="bookid", insertable=false, updatable=false)
    private Books      books ; 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(hassaleid);
        sb.append("|");
        sb.append(bookid);
        sb.append("|");
        sb.append(saleid);
        sb.append("|");
        sb.append(starttime);
        sb.append("|");
        sb.append(endtime);
        return sb.toString(); 
    } 

}
