/*
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.DATN_BookWorms.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Hassales"
 *
 * @author Telosys
 *
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
@Table(name="HasSales", schema="dbo", catalog="BookWorm" )
public class Hassales implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="HasSaleId", nullable=false)
    private Integer    hassaleid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="BookId", nullable=false)
    private Integer    bookid ;

    @Column(name="SaleId", nullable=false, length=10)
    private String     saleid ;

    @Temporal(TemporalType.DATE)
    @Column(name="StartTime")
    private Date       starttime ;

    @Temporal(TemporalType.DATE)
    @Column(name="EndTime")
    private Date       endtime ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="BookId", referencedColumnName="BookId", insertable=false, updatable=false)
    private Books      books ; 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(hassaleid);
        sb.append("|");
        sb.append(bookid);
        sb.append("|");
        sb.append(saleid);
        sb.append("|");
        sb.append(starttime);
        sb.append("|");
        sb.append(endtime);
        return sb.toString(); 
    } 

}
