/*
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.DATN_BookWorms.entities;

import java.io.Serializable;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Imagebooks"
 *
 * @author Telosys
 *
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
@Table(name="Imagebooks")
public class ImageBook implements Serializable {

    public static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
    public Integer    filedid ;

    //--- ENTITY DATA FIELDS 

    public String     name ;

    public String     typefile ;

    public Integer    bookid ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="Bookid", referencedColumnName="BookId", insertable=false, updatable=false)
    public Book      book ;

    @Override
    public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("|");
		sb.append(name);
		sb.append("|");
		sb.append(typefile);
		sb.append("|");
		sb.append(bookid);
		return sb.toString();
	}
}