/*
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.DATN_BookWorms.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Orderstatuses"
 *
 * @author Telosys
 *
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
@Table(name="OrderStatuses", schema="dbo", catalog="BookWorm" )
public class Orderstatuses implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="OrderStatusId", nullable=false)
    private Integer    orderstatusid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="StatusName", length=50)
    private String     statusname ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="orderstatuses")
    private List<Bookings> listOfBookings ; 
    
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(orderstatusid);
        sb.append("|");
        sb.append(statusname);
        return sb.toString(); 
    } 

}
