/*
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.DATN_BookWorms.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Paymentaccounts"
 *
 * @author Telosys
 *
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
@Table(name="PaymentAccounts", schema="dbo", catalog="BookWorm" )
public class Paymentaccounts implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="PAId", nullable=false, length=10)
    private String     paid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="UserId", nullable=false, length=10)
    private String     userid ;

    @Column(name="Name", length=30)
    private String     name ;

    @Column(name="CCCD", length=12)
    private String     cccd ;

    @Column(name="BankName", length=100)
    private String     bankname ;

    @Column(name="AccountNumber", length=20)
    private String     accountnumber ;

    @Column(name="AccountName", length=30)
    private String     accountname ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="paymentaccounts")
    private List<Payments> listOfPayments ; 

    @ManyToOne
    @JoinColumn(name="UserId", referencedColumnName="Userid", insertable=false, updatable=false)
    private Account    account ; 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(paid);
        sb.append("|");
        sb.append(userid);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(cccd);
        sb.append("|");
        sb.append(bankname);
        sb.append("|");
        sb.append(accountnumber);
        sb.append("|");
        sb.append(accountname);
        return sb.toString(); 
    } 

}
