/*
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.DATN_BookWorms.entities;

import java.io.Serializable;
import java.util.List;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Paymentaccounts"
 *
 * @author Telosys
 *
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
@Table(name="paymentaccounts", schema="dbo", catalog="bookworm" )
public class Paymentaccounts implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="paid", nullable=false, length=10)
    private String     paid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="userid", nullable=false, length=10)
    private String     userid ;

    @Column(name="name", length=30)
    private String     name ;

    @Column(name="cccd", length=12)
    private String     cccd ;

    @Column(name="bankname", length=100)
    private String     bankname ;

    @Column(name="accountnumber", length=20)
    private String     accountnumber ;

    @Column(name="accountname", length=30)
    private String     accountname ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="paymentaccounts")
    private List<Payments> listOfPayments ; 

    @ManyToOne
    @JoinColumn(name="userid", referencedColumnName="userid", insertable=false, updatable=false)
    private Account    account ; 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(paid);
        sb.append("|");
        sb.append(userid);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(cccd);
        sb.append("|");
        sb.append(bankname);
        sb.append("|");
        sb.append(accountnumber);
        sb.append("|");
        sb.append(accountname);
        return sb.toString(); 
    } 

}
