/*
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.DATN_BookWorms.entities;

import java.io.Serializable;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Roles"
 *
 * @author Telosys
 */

@Data
@Entity
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "Roles")
public class Role implements Serializable {
    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    private String roleid;

    //--- ENTITY DATA FIELDS 
    private String rolename;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy = "role")
    @JsonIgnore
    private List<Authority> listOfAuthority;

    //--- toString specific method
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(roleid);
        sb.append("|");
        sb.append(rolename);
        return sb.toString();
    }
}