/*
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.DATN_BookWorms.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * JPA entity class for "Sales"
 *
 * @author Telosys
 *
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
@Table(name="Sales")
public class Sales implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    public String     couoponcode ;

    //--- ENTITY DATA FIELDS 
    public String     promotionname ;

    @Temporal(TemporalType.DATE)
    public Date       createat ;
    
    @Temporal(TemporalType.DATE)
    public Date       enddiscount ;

    @Column(name="descriptions", length=255)
    public String     descriptions ;

    public BigDecimal discountpercentage ;

    @Column(name="statuses", length=20)
    public String     statuses ;

    public String     intendfor ;

    public Integer    shopid ;
    
    public Double     minprice ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="sales")
    @JsonIgnore
    public List<Discountcodes> listOfDiscountcodes ; 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(couoponcode);
        sb.append("|");
        sb.append(promotionname);
        sb.append("|");
        sb.append(createat);
        sb.append("|");
        sb.append(descriptions);
        sb.append("|");
        sb.append(discountpercentage);
        sb.append("|");
        sb.append(statuses);
        sb.append("|");
        sb.append(intendfor);
        sb.append("|");
        sb.append(shopid);
        return sb.toString(); 
    }

	public String getCouoponcode() {
		return couoponcode;
	}

	public void setCouoponcode(String couoponcode) {
		this.couoponcode = couoponcode;
	}

	public String getPromotionname() {
		return promotionname;
	}

	public void setPromotionname(String promotionname) {
		this.promotionname = promotionname;
	}

	public Date getCreateat() {
		return createat;
	}

	public void setCreateat(Date createat) {
		this.createat = createat;
	}

	public Date getEnddiscount() {
		return enddiscount;
	}

	public void setEnddiscount(Date enddiscount) {
		this.enddiscount = enddiscount;
	}

	public String getDescriptions() {
		return descriptions;
	}

	public void setDescriptions(String descriptions) {
		this.descriptions = descriptions;
	}

	public BigDecimal getDiscountpercentage() {
		return discountpercentage;
	}

	public void setDiscountpercentage(BigDecimal discountpercentage) {
		this.discountpercentage = discountpercentage;
	}

	public String getStatuses() {
		return statuses;
	}

	public void setStatuses(String statuses) {
		this.statuses = statuses;
	}

	public String getIntendfor() {
		return intendfor;
	}

	public void setIntendfor(String intendfor) {
		this.intendfor = intendfor;
	}

	public Integer getShopid() {
		return shopid;
	}

	public void setShopid(Integer shopid) {
		this.shopid = shopid;
	}

	public Double getMinprice() {
		return minprice;
	}

	public void setMinprice(Double minprice) {
		this.minprice = minprice;
	}

	public List<Discountcodes> getListOfDiscountcodes() {
		return listOfDiscountcodes;
	}

	public void setListOfDiscountcodes(List<Discountcodes> listOfDiscountcodes) {
		this.listOfDiscountcodes = listOfDiscountcodes;
	} 

}