/*
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.DATN_BookWorms.entities;

import java.io.Serializable;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Typebooks"
 *
 * @author Telosys
 *
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
@Table(name = "Typebooks")
public class TypeBook implements Serializable {
	private static final long serialVersionUID = 1L;

	// --- ENTITY PRIMARY KEY
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Integer typebookid;

	// --- ENTITY DATA FIELDS
	public Integer bookid;

	public Integer categoryid;

	// --- ENTITY LINKS ( RELATIONSHIP )
	@ManyToOne
	@JoinColumn(name = "Bookid", referencedColumnName = "BookId", insertable = false, updatable = false)
	public Book book;

	@ManyToOne
	@JoinColumn(name = "Categoryid", referencedColumnName = "CategoryId", insertable = false, updatable = false)
	public Category category;

	// --- toString specific method
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(typebookid);
		sb.append("|");
		sb.append("|");
		sb.append(bookid);
		return sb.toString();
	}
}