/*
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.DATN_BookWorms.entities;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Typebooks"
 *
 * @author Telosys
 *
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
@Table(name = "typebooks", schema = "dbo", catalog = "bookworm")
public class Typebooks implements Serializable {

	private static final long serialVersionUID = 1L;

	// --- ENTITY PRIMARY KEY
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "typebookid", nullable = false)
	private Integer typebookid;

	// --- ENTITY DATA FIELDS
	@Column(name = "categoryid")
	private Integer categoryid;

	@Column(name = "bookid")
	private Integer bookid;

	// --- ENTITY LINKS ( RELATIONSHIP )
	@ManyToOne
	@JoinColumn(name = "bookid", referencedColumnName = "bookid", insertable = false, updatable = false)
	private Books books;

	@ManyToOne
	@JoinColumn(name = "categoryid", referencedColumnName = "categoryid", insertable = false, updatable = false)
	private Categories categories;

	// --- toString specific method
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(typebookid);
		sb.append("|");
		sb.append(categoryid);
		sb.append("|");
		sb.append(bookid);
		return sb.toString();
	}

}
