/*
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.poly.DATN_BookWorms.entities;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Writers"
 *
 * @author Telosys
 *
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
@Table(name="writers", schema="dbo", catalog="bookworm" )
public class Writers implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="writeid", nullable=false)
    private Integer    writeid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="writtingmasterid", nullable=false)
    private Integer    writtingmasterid ;

    @Column(name="bookid", nullable=false)
    private Integer    bookid ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="bookid", referencedColumnName="bookid", insertable=false, updatable=false)
    private Books      books ; 

    @ManyToOne
    @JoinColumn(name="writtingmasterid", referencedColumnName="writtingmasterid", insertable=false, updatable=false)
    private Writtingmasters writtingmasters ; 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(writeid);
        sb.append("|");
        sb.append(writtingmasterid);
        sb.append("|");
        sb.append(bookid);
        return sb.toString(); 
    } 

}
